apiVersion : apps/v1
kind: Deployment
metadata:
  name: christmascountdown 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: christmascountdown
  template:
    metadata:
      labels:
        app: christmascountdown 
    spec:
      containers:
        - name: sampleapp 
          image: christmascountdownregistry.azurecr.io/christmascountdown
          ports:
          - containerPort: 80